# Generated by Django 5.1.5 on 2025-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.ImageField(blank=True, default='No_image_available.jpg', null=True, upload_to='brand')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING')], default='PUBLISHED', max_length=255)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
